version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: threatlens-backend-prod
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///data/threatlens.db
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LOG_LEVEL=WARNING
      - WORKERS=4
    volumes:
      - threatlens-data:/app/data
      - threatlens-logs:/app/logs
    networks:
      - threatlens-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: threatlens-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - threatlens-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # Optional: Add reverse proxy for SSL termination
  nginx-proxy:
    image: nginx:alpine
    container_name: threatlens-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    networks:
      - threatlens-network
    restart: always
    profiles:
      - ssl

networks:
  threatlens-network:
    driver: bridge

volumes:
  threatlens-data:
    driver: local
  threatlens-logs:
    driver: local