services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: threatlens-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///data/threatlens.db
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LOG_LEVEL=INFO
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      - ./backend/app:/app/app:ro  # Read-only for development
    networks:
      - threatlens-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-simple"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: threatlens-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - threatlens-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  threatlens-network:
    driver: bridge

volumes:
  threatlens-data:
    driver: local